"""
Phase 7.4 — Evidence Card Builder
----------------------------------

Combines:
- Fusion prediction (Phase 6)
- Sentiment & clickbait (Phase 5)
- Text XAI (Phase 7.1)
- Grad-CAM heatmap (Phase 7.2)
- Counterfactual analysis (Phase 7.3)

Outputs structured evidence card JSON.
"""

import json
import sys
from pathlib import Path
from typing import Dict, Any

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.append(str(PROJECT_ROOT))

# Fusion inference
from src.fusion.infer import predict_sample

# Framing features
from src.framing.sentiment import analyze_sentiment
from src.framing.clickbait import clickbait_score as analyze_clickbait

# XAI
from src.xai.text import explain_text
from src.xai.counterfactuals import run_counterfactuals

# -----------------------------
# CONFIG
# -----------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
CARDS_DIR = ARTIFACTS_DIR / "cards"
GRADCAM_DIR = ARTIFACTS_DIR / "xai"

CARDS_DIR.mkdir(parents=True, exist_ok=True)


# -----------------------------
# Root Cause Heuristics
# -----------------------------

def infer_root_causes(features: Dict[str, float]) -> list:
    causes = []

    if features.get("clickbait", 0) > 0.5:
        causes.append("sensational_framing")

    if features.get("vlm_consistency", 1.0) < 0.4:
        causes.append("image_text_mismatch")

    if features.get("rag_contradict", 0) > 0.6:
        causes.append("external_contradiction")

    if features.get("subjectivity", 0) > 0.7:
        causes.append("high_subjectivity")

    if not causes:
        causes.append("no_strong_signal")

    return causes


# -----------------------------
# Build Evidence Card
# -----------------------------

def build_evidence_card(sample: Dict[str, Any]) -> Dict[str, Any]:
    """
    sample expects:
    {
        "id": str,
        "image_path": str,
        "post_text": str,
        "features": {...}  # fusion features
    }
    """

    # 1️⃣ Fusion prediction
    fusion_output = predict_sample(sample["features"])

    # 2️⃣ Framing signals
    sent = analyze_sentiment(sample["post_text"])
    click = analyze_clickbait(sample["post_text"])

    # 3️⃣ Text XAI
    text_explanation = explain_text(sample["post_text"], target_label="fake")

    # 4️⃣ Counterfactuals
    cf = run_counterfactuals(sample["features"])

    # 5️⃣ Grad-CAM path (if exists)
    heatmap_path = GRADCAM_DIR / f"gradcam_{sample['id']}.png"
    heatmap_str = str(heatmap_path) if heatmap_path.exists() else None

    # 6️⃣ Root cause inference
    root_causes = infer_root_causes(sample["features"])

    card = {
        "id": sample["id"],
        "final_label": fusion_output["label"],
        "credibility": round(fusion_output["confidence"], 4),
        "root_causes": root_causes,
        "evidence": [
            {
                "rag_support": sample["features"].get("rag_support"),
                "rag_contradict": sample["features"].get("rag_contradict")
            }
        ],
        "framing": {
            "sentiment": sent["sentiment"],
            "subjectivity": sent["subjectivity"],
            "clickbait_score": click["clickbait"]
        },
        "xai": {
            "top_text_tokens": text_explanation,
            "image_heatmap_path": heatmap_str
        },
        "counterfactuals": cf,
        "notes": "Generated by Phase 7 evidence builder"
    }

    return card


# -----------------------------
# Save Card
# -----------------------------

def save_card(card: Dict[str, Any]):
    out_path = CARDS_DIR / f"{card['id']}_card.json"
    with open(out_path, "w") as f:
        json.dump(card, f, indent=2)
    print(f"[WROTE] {out_path}")


# -----------------------------
# Main (Sanity Test)
# -----------------------------

def main():
    print("\n[Phase 7.4] Evidence Card Sanity Check")
    print("-" * 60)

    # Example sample (adjust features if needed)
    sample = {
        "id": "demo_001",
        "image_path": None,
        "post_text": "SHOCKING truth they don't want you to know!!!",
        "features": {
            "text_cls_score": 0.3,
            "rag_support": 0.2,
            "rag_contradict": 0.8,
            "vlm_consistency": 0.25,
            "vlm_entropy": 1.1,
            "ocr_match": 0.0,
            "sentiment": 0.2,
            "subjectivity": 0.8,
            "clickbait": 0.7,
            "text_length_norm": 0.2,
            "has_image": 1
        }
    }

    card = build_evidence_card(sample)
    save_card(card)

    print("\nGenerated Card:")
    print(json.dumps(card, indent=2))


if __name__ == "__main__":
    main()
